istio:
    enabled: false

frontend:
    replicas: 1
    image:
        repo: socksshop/front-end
        tag: latest
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi
    hpa:
        minReplicas: 1
        maxReplicas: 2
        cpuTargetUtilization: 80
        memoryTargetUtilization: 80
