zipkincron:
    image:
        repo: openzipkin/zipkin-dependencies
        tag: 1.4.0
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi

zipkin:
    image:
        repo: openzipkin/zipkin
        tag: 2.21
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi
    enabled:  false
    url: zipkin.zipkin.svc.cluster.local

zipkinmysql:
    image:
        repo: openzipkin/zipkin-mysql
        tag: 1.20.0
    resources:
        requests:
            memory: 256Mi
            cpu: 250m
        limits:
            memory: 768Mi
            cpu: 1
