---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    name: user-db
spec:
  replicas: {{ .Values.userdb.replicas }}
  selector:
    matchLabels:
      name: user-db
  template:
    metadata:
      labels:
        name: user-db
    spec:
      securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
      containers:
      - name: user-db
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.userdb.image.repo }}:{{ .Values.userdb.image.tag }}
        ports:
        - name: mongo
          containerPort: 27017
        resources:
{{ toYaml .Values.userdb.resources | indent 10 }}
        command: ["mongod"]
        args: ["--dbpath", "/data/db", "--smallfiles"]
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /data/db
          name: user-db-storage
      volumes:
        - name: user-db-storage
          persistentVolumeClaim:
            claimName: user-db-pvc
