apiVersion: v1
description: A Helm chart for Sock Shop microservices (except frontend)
name: helm-chart
version: 0.3.0

# dependencies:
#   - name: nginx-ingress
#     version: "2.0.0"
#     repository: "https://helm.nginx.com/stable"
