nameOverride: user-db

psmdb:
  clusterName: user-db

  image:
    repository: percona/percona-server-mongodb
    tag: 6.0.8-9

  replsets:
    - name: rs0
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
          storageClassName: gp2
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"

  expose:
    exposeType: ClusterIP
    customService:
      metadata:
        name: user-db
      spec:
        selector:
          app.kubernetes.io/name: psmdb-db
          app.kubernetes.io/component: mongod
          app.kubernetes.io/instance: user-db
        ports:
          - port: 27017
            targetPort: 27017

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001

  backup:
    enabled: false

  deletePVC: true
