nameOverride: user-db

crVersion: 1.20.0

image:
  repository: percona/percona-server-mongodb
  tag: 7.0.18-11

replsets:
  rs0:
    name: rs0
    size: 3
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    labels:
      app.kubernetes.io/instance: user-db
      app.kubernetes.io/name: psmdb-db
      app.kubernetes.io/component: mongod
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp3
    expose:
      enabled: true
      type: ClusterIP
      customService:
        metadata:
          name: user-db
        spec:
          selector:
            app.kubernetes.io/instance: user-db
            app.kubernetes.io/name: psmdb-db
            app.kubernetes.io/component: mongod
          ports:
            - port: 27017
              targetPort: 27017
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    podDisruptionBudget:
      maxUnavailable: 1

    initImage:
      repository: socksshop/user-db-restore
      tag: latest

users:
  - name: userAdmin # Le nom de l'utilisateur que l'opérateur utilise par défaut
    passwordSecretRef: # RÉFÉRENCE AU NOUVEAU SECRET AVEC VALEURS VIDES
      name: user-db-empty-secrets # <--- C'est le Secret que nous venons de créer
      key: MONGODB_USER_ADMIN_PASSWORD # La clé pour le mot de passe vide
    roles:
      - name: userAdminAnyDatabase # Rôle pour gérer les utilisateurs sur toutes les BD
        db: admin
      - name: readWriteAnyDatabase # Rôle pour lire/écrire sur TOUTES les BD
        db: admin

sharding:
  enabled: false

backup:
  enabled: false
