nameOverride: orders-db

replsets:
  rs0:
    name: rs0
    size: 3
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2
    expose:
      enabled: true
      type: ClusterIP
      customService:
        metadata:
          name: orders-db
        spec:
          selector:
            app.kubernetes.io/name: psmdb-db
            app.kubernetes.io/component: mongod
            app.kubernetes.io/instance: orders-db
          ports:
            - port: 27017
              targetPort: 27017
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    podDisruptionBudget:
      maxUnavailable: 1

sharding:
  enabled: true

backup:
  enabled: false
