queuemaster:
    image:
        repo: weaveworksdemos/queue-master
        tag: 0.3.1
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 300m
            memory: 1000Mi
