apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carts-db-pvc
  labels:
    app: carts-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
