---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  labels:
    name: carts-db
spec:
  replicas: {{ .Values.cartsdb.replicas }}
  selector:
    matchLabels:
      name: carts-db
  template:
    metadata:
      labels:
        name: carts-db
    spec:
      securityContext:
          fsGroup: 999
      containers:
      - name: carts-db
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.cartsdb.image.repo }}:{{ .Values.cartsdb.image.tag }}
        ports:
        - name: mongo
          containerPort: 27017
        resources:
{{ toYaml .Values.cartsdb.resources | indent 10 }}
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /data/db
          name: carts-db-storage
      volumes:
        - name: carts-db-storage
          persistentVolumeClaim:
            claimName: carts-db-pvc
