---
apiVersion: v1
kind: Service
metadata:
  name: carts-db-headless # CHANGEMENT: Renommé pour être explicite
  labels:
    name: carts-db
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  clusterIP: None # AJOUT IMPORTANT: Rend le service headless
  selector:
    name: carts-db
