apiVersion: v1
kind: Service
metadata:
  name: carts
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
  labels:
    name: carts
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.carts.containerPort }}
  selector:
    name: carts
