# secrets/catalogue-db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: catalogue-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
