---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
spec:
  replicas: {{ .Values.ordersdb.replicas }}
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      securityContext:
          fsGroup: 999
      containers:
      - name: orders-db
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.ordersdb.image.repo }}:{{ .Values.ordersdb.image.tag }}
        ports:
        - name: mongo
          containerPort: 27017
        resources:
{{ toYaml .Values.ordersdb.resources | indent 10 }}
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /data/db
          name: orders-db-storage
      volumes:
        - name: orders-db-storage
          persistentVolumeClaim:
            claimName: orders-db-pvc
