apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: {{ .Values.payment.hpa.minReplicas | default "1" }}
  maxReplicas: {{ .Values.payment.hpa.maxReplicas | default "2" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.payment.hpa.cpuTargetUtilization | default "80" }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.payment.hpa.memoryTargetUtilization | default "80" }}
