---
apiVersion: v1
kind: Service
metadata:
  name: payment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.payment.containerPort }}"
  labels:
    name: payment
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: { { .Values.payment.containerPort } }
  selector:
    name: payment
