---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-db
  labels:
    name: session-db
spec:
  replicas: {{ .Values.sessiondb.replicas }}
  selector:
    matchLabels:
      name: session-db
  template:
    metadata:
      labels:
        name: session-db
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: session-db
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.sessiondb.image.repo }}:{{ .Values.sessiondb.image.tag }}
        ports:
        - name: redis
          containerPort: 6379
        command: ["redis-server"]
        args: ["--appendonly", "yes", "--appendfsync", "everysec", "--dir", "/data"]
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        resources:
{{ toYaml .Values.sessiondb.resources | indent 10 }}
        volumeMounts:
        - mountPath: /data
          name: session-db-storage
      volumes:
        - name: session-db-storage
          persistentVolumeClaim:
            claimName: session-db-pvc
