---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: session-db
  labels:
    name: session-db
spec:
  serviceName: session-db
  replicas: 1
  selector:
    matchLabels:
      name: session-db
  template:
    metadata:
      labels:
        name: session-db
    spec:
      containers:
      - name: session-db
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.sessiondb.image.repo }}:{{ .Values.sessiondb.image.tag }}
        ports:
        - name: redis
          containerPort: 6379
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        resources:
{{ toYaml .Values.sessiondb.resources | indent 10 }}
        volumeMounts:
            - mountPath: /data
              name: session-db-pvc
  volumeClaimTemplates:
    - metadata:
        name: session-db-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.sessiondb.persistentVolume.size }}
        # storageClassName: local-path # FOR LOCAL DEPLOIMENT (delete for AWS DEPLOYMENT)
