apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-db-pvc
  labels:
    app: session-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
