---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
  labels:
    name: shipping
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: {{ .Values.shipping.containerPort }}
  selector:
    name: shipping
