---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user
  template:
    metadata:
      labels:
        name: user
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.user.metricsPort | default .Values.user.containerPort }}"
        prometheus.io/path: "/metrics"
      {{- if .Values.istio.enabled }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      {{- end }}
    spec:
      containers:
      - name: user
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.user.image.repo }}:{{ .Values.user.image.tag }}
        command:
        - /user
        args:
        - -port={{ .Values.user.containerPort }}
        - -database=mongodb
        - -mongo-host=user-db.{{ .Release.Namespace }}.svc.cluster.local:27017/?replicaSet=rs0
        resources:
{{ toYaml .Values.user.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.user.containerPort }}
          name: http
        - containerPort: {{ .Values.user.metricsPort | default .Values.user.containerPort }}
          name: metrics
        env:
        - name: MONGO_HOST
          value: user-db:27017/?replicaSet=rs0
        {{- if .Values.zipkin.enabled }}
        - name: ZIPKIN
          value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
{{- if lt (int .Values.user.containerPort) 1024 }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
{{- end }}
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.user.containerPort }}
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.user.containerPort }}
          initialDelaySeconds: 180
          periodSeconds: 3
