apiVersion: v1
kind: Service
metadata:
  name: user-db-headless
  labels:
    name: user-db
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: user-db
