apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: catalogue-db
  namespace: percona-mysql
spec:
  crVersion: 1.16.1
  image: percona/percona-xtradb-cluster:8.0.26
  imagePullPolicy: Always
  updateStrategy: SmartUpdate

  secrets:
    users: ""
    encryptionKey: s3-backups-encryption-key

  replsets:
    - name: catalogue-replica
      size: 2
      expose:
        enabled: true
      volumeSpec:
        persistentVolumeClaim:
          accessModes: ["ReadWriteOnce"]
          # storageClassName: local-path # FOR LOCAL PURPOSE
          resources:
            requests:
              storage: 512Mi
      containerSecurityContext:
        capabilities:
          drop: ["ALL"]
          add: ["CHOWN", "SETGID", "SETUID"]
        readOnlyRootFilesystem: true
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: fake_password
        - name: MYSQL_DATABASE
          value: socksdb

  service:
    name: catalogue-db

  backup:
    enabled: true
    image: percona/percona-xtradb-cluster-backup:8.0.26
    storages:
      s3-us-east:
        type: s3
        s3:
          bucket: sockshop-mysql-backups-bucket
          region: us-east-1
          credentialsSecret: aws-credentials
    tasks:
      - name: daily-backup
        enabled: true
        schedule: "0 2 * * *"
        keep: 7
        storageName: s3-us-east
