apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: user-db
  namespace: percona-mongodb
spec:
  crVersion: 1.13.0
  image: percona/percona-server-mongodb:4.4.22-22
  imagePullPolicy: Always
  updateStrategy: SmartUpdate

  sharding:
    enabled: false

  secrets:
    users: ""  # pas de mot de passe
    encryptionKey: s3-backups-encryption-key

  replsets:
    - name: user-replica
      size: 2
      expose:
        enabled: true
      volumeSpec:
        persistentVolumeClaim:
          accessModes: ["ReadWriteOnce"]
          # storageClassName: local-path # FOR LOCAL PURPOSE
          resources:
            requests:
              storage: 512Mi
      containerSecurityContext:
        capabilities:
          drop: ["ALL"]
          add: ["CHOWN", "SETGID", "SETUID"]
        readOnlyRootFilesystem: true
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"

  service:
    name: user-db

  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      enabled: false
    storages:
      s3-us-east:
        type: s3
        s3:
          bucket: sockshop-mongo-backups-bucket
          region: us-east-1
          credentialsSecret: aws-credentials
    tasks:
      - name: daily-backup
        enabled: true
        schedule: "0 2 * * *"
        keep: 7
        storageName: s3-us-east
