ordersdb:
    image:
        repo: mongo
        tag: 4.4.0
    resources:
        requests:
            cpu: 500m
            memory: 512Mi
        limits:
            cpu: 500m
            memory: 512Mi

orders:
    image:
        repo: weaveworksdemos/orders
        tag: 0.4.7
    containerPort: 80
    metricsPort: 8080
    resources:
        limits:
            cpu: 500m
            memory: 2000Mi
        requests:
            cpu: 200m
            memory: 2000Mi
