apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "user-db-restore.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
