apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name | default "default-release" }}-socks-ingress
  namespace: dev
  labels:
    {{ toYaml .Values.ingress.labels | indent 4 }}
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/load-balancer-attributes: |
      deletion_protection.enabled=false
    alb.ingress.kubernetes.io/group.name: sockshop-main-alb
spec:
  ingressClassName: alb
  rules:
  - host: www.sockshop.loseyourip.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
