apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
{{ toYaml .Values.ingress.labels | indent 4 }}
  name: {{ .Release.Name }}-socks-ingress
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: front-end
            port:
              number: 80
        path: /
        pathType: Prefix
    {{- if .Values.host }}
    host: {{ .Values.ingress.host }}
    {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    {{- if .Values.host }}
    hosts:
    - {{ .Values.ingress.host }}
    {{- end }}
  {{- end }}
