apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    ttl: 168h
    includedNamespaces:
    - 'dev'
    - 'staging'
    - 'prod'
