apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  labels:
    app: mongodb-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.backup.serviceAccountName }}
          containers:
          - name: mongodb-backup
            image: socksshop/socksshop-mongo:1.0
            command:
              - /bin/sh
              - -c
              - |
                echo "Démarrage du backup MongoDB..."
                mongodump --forceTableScan --host {{ .Values.mongo.host }} --out /backup
                echo "Envoi du backup vers S3..."
                aws s3 cp /backup s3://{{ .Values.backup.bucketName }}/mongodb/$(date +\%Y-\%m-\%d) --recursive
          restartPolicy: OnFailure