apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-credentials-sa
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backup
    meta.helm.sh/release-namespace: default
    eks.amazonaws.com/role-arn: arn:aws:iam::870189691154:role/S3WriteRole