apiVersion: v2
name: monitoring
description: Helm chart pour déployer le monitoring de stack avec Prometheus et Grafana
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: 70.4.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 8.11.4
    repository: https://grafana.github.io/helm-charts