loadtest:
    replicas: 2
    enabled: false
    image:
        repo: weaveworksdemos/load-test
        tag: 0.1.1
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi
