userdb:
    image:
        repo: weaveworksdemos/user-db
        tag: 0.4.0
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi

user:
    image:
        repo: weaveworksdemos/user
        tag: 0.4.7
    containerPort: 80
    metricsPort: 8080
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 400Mi
